### ISSUE TITLE
Abyssal not Present in Obsidian Theme Viewer

### ISSUE THREAD

**Issue by micwaab** [tazpellegrini/abyssalobsidian#1]
Hello,

Very excited to check out your beautiful theme. Unfortunately, it's not showing up under appearance/manage/search for "Abyssal".

**Comment by tazpellegrini** [comment]
Thank you! I really appreciate your comment. You’re right; It’s not there because the Obsidian team haven’t merged my request with their repository yet. Hopefully soon! I’m keeping an eye constantly in case any problem appears so it is fixed ASAP. 

Meanwhile, you can do a manual install instead (but I would recommend using the Themes tab whenever it is available so any updates can be received more easily) by: 

- Download the `theme.css` file
- Navigate to the vault you would like to install this theme
- Create a folder called Abyssal inside the `.obsidian folder > Themes` in your vault (make sure dot files/folders are displayed; on macOS this can be done by pressing `CMD + Shift + .` while on Finder)
- Paste the `theme.css` inside the newly created Abyssal folder
- Open Obsidian, then `Settings > Appearance`. Choose ”Abyssal” under the `Themes` dropdown

I would recommend waiting until Abyssal is merged and neatly appears on the official theme store for reasons I mentioned before, but out of curiosity, that’s how themes are manually installed :) 

Have a nice day!

**Comment by micwaab** [comment]
Thank you! I really appreciate your message. I'll be patient and wait for it to show up within Obsidian. Looks like a beautiful theme!

**Comment by tazpellegrini** [comment]
@micwaab the theme is now there 🚀 thanks for your kind words, and you’re always welcome to share any issues or feedback. Cheers!
